version: '2.3'
services:
  # This is the list of services and containers that make our application
  # for more Data Science projects, you will probably have one container
  notebook:
    build:
      dockerfile: Dockerfile
      context: .
    image: jupyter/scipy-notebook
    command: start-notebook.sh --NotebookApp.password='sha1:d3425fef85a2:b958281342f59ca4f7571c7a01c62ea70576456d'
    environment: # see https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html for options
      - "GRANT_SUDO=yes"
      - "JUPYTER_ENABLE_LAB=yes"
      # Change the default UID. needed on linux for file permissions
      - "NB_UID=${NB_UID:-1000}"
      - "NB_GID=${NB_GID:-100}"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    user: root
